#!/usr/bin/env bash
#
# kpcu-read - wrapper around kreadconfig5

POSITIONAL_ARGS=()
KEY_GROUPS=()

while [ $# -gt 0 ]; do
    case $1 in
        -f|--file)
            FILE=$2
            shift 2
            ;;
        -t|--type)
            TYPE=$2
            shift 2
            ;;
        -h|--help)
            HELP=1
            shift
            ;;
        -g|--group|/)
            KEY_GROUPS+=( '--group' "$2" )
            shift 2
            ;;
        -*)
            echo "Unknown option $1"
            exit 1
            ;;
        *)
            # save positional arg
            POSITIONAL_ARGS+=("$1")
            shift
            ;;
    esac
done

# restore positional parameters
set -- "${POSITIONAL_ARGS[@]}"

if [[ -n "$HELP" ]] || [[ "$#" -lt 1 ]]; then
    cat <<EOF
Usage: $0 [<arguments...>] <key> [<default value>]

Arguments:
    -f/--file       Path to file to write to (defaults to global)
    -t/--type       Type to read the value as (read 'kreadconfig5' help page)
    -h/--help       Shows this message
    -g/--group      Group the key is contained in, can be chained (alias: /)

Examples:
    # read panel thickness
    \$ $0 -f ~/.config/plasmashellrc / PlasmaViews / 'Panel 2' / 'Defaults' thickness

    # read open by single click instead of double click
    \$ $0 -f ~/.config/kdeglobals / KDE -t bool SingleClick

EOF

    exit 0
fi

ARGS=()

if [[ "${#KEY_GROUPS[@]}" -gt 0 ]]; then
    ARGS+=( "${KEY_GROUPS[@]}" )
fi

if [[ -n "$FILE" ]]; then
    ARGS+=( '--file' "$FILE" )
fi

if [[ -n "$TYPE" ]]; then
    ARGS+=( '--type' "$TYPE" )
fi

if [[ -n "$2" ]]; then
    ARGS+=( '--default' "$2" )
fi

kreadconfig5 "${ARGS[@]}" --key "$1"

